export type Locale = "zh-Hans" | "zh-Hant" | "en";

export const LOCALES: { value: Locale; label: string }[] = [
  { value: "zh-Hans", label: "简体中文" },
  { value: "zh-Hant", label: "繁體中文" },
  { value: "en", label: "English" },
];

type Dict = Record<string, string>;

const en: Dict = {
  "app.name": "Campus Meals",
  "app.tagline": "Made for college students",

  "tabs.thisWeek": "This Week",
  "tabs.grocery": "Groceries",
  "tabs.preferences": "Prefs",
  "tabs.settings": "Settings",

  "common.loading": "Loading...",
  "common.today": "Today",
  "common.current": "Current",
  "common.cancel": "Cancel",
  "common.done": "Done",
  "common.close": "Close",
  "common.back": "Back",
  "common.serving": "serving",
  "common.servings": "servings",

  "week.title": "This Week",
  "week.empty.title": "No meals planned yet",
  "week.empty.text": "Generate a fresh week of simple, tasty meals tailored to your preferences.",
  "week.generate": "Generate New Week",

  "meal.breakfast": "Breakfast",
  "meal.lunch": "Lunch",
  "meal.dinner": "Dinner",

  "grocery.title": "Grocery List",
  "grocery.progress": "{checked} of {total} items checked",
  "grocery.clearDone": "Clear Done",
  "grocery.share": "Share",
  "grocery.empty.title": "No groceries yet",
  "grocery.empty.text": "Generate a meal plan first, and your shopping list will appear here automatically.",

  "category.Produce": "Produce",
  "category.Dairy": "Dairy",
  "category.Pantry": "Pantry",
  "category.Protein": "Protein",
  "category.Frozen": "Frozen",
  "category.Other": "Other",

  "prefs.title": "Preferences",
  "prefs.subtitle": "These settings will shape your next generated meal plan.",
  "prefs.dietary": "Dietary Restrictions",
  "prefs.meals": "Meals Per Day",
  "prefs.budget": "Weekly Budget Goal",
  "prefs.skill": "Cooking Comfort Level",

  "diet.vegetarian": "Vegetarian",
  "diet.vegan": "Vegan",
  "diet.gf": "Gluten-Free",
  "diet.df": "Dairy-Free",

  "skill.Beginner": "Beginner",
  "skill.Intermediate": "Intermediate",
  "skill.Confident": "Confident",

  "budget.Tight": "Tight ($30)",
  "budget.Moderate": "Moderate ($60)",
  "budget.Comfortable": "Comfortable ($100)",

  "meals.Dinner": "Dinner Only",
  "meals.Lunch+Dinner": "Lunch + Dinner",
  "meals.All": "All Three",

  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.theme": "Theme Color",
  "settings.themeHint": "Pick an accent color for the app.",

  "theme.red": "Red",
  "theme.orange": "Orange",
  "theme.yellow": "Yellow",
  "theme.cyan": "Cyan",
  "theme.blue": "Blue",
  "theme.purple": "Purple",
  "theme.pink": "Pink",

  "recipe.notFound": "Recipe not found.",
  "recipe.goBack": "Go Back",
  "recipe.ingredients": "Ingredients",
  "recipe.instructions": "Instructions",
  "recipe.swap": "Swap this meal",
  "recipe.minutes": "{n}m",

  "share.title": "Share Your Plan",
  "share.subtitle": "A snapshot of this week's menu and grocery list.",
  "share.preview.header": "This Week's Menu",
  "share.preview.grocery": "Grocery List",
  "share.preview.items": "{n} items",
  "share.preview.more": "+ {n} more",
  "share.preview.footer": "Generated by Campus Meals",
  "share.save": "Save Image",
  "share.send": "Share",
  "share.saved": "Saved to Photos",
  "share.savedFail": "Could not save image.",
  "share.permission": "Photo permission denied.",
  "share.shareFail": "Sharing not available.",
  "share.webOnly": "Image preview shown above.",

  "day.0.short": "Sun",
  "day.1.short": "Mon",
  "day.2.short": "Tue",
  "day.3.short": "Wed",
  "day.4.short": "Thu",
  "day.5.short": "Fri",
  "day.6.short": "Sat",
};

const zhHans: Dict = {
  "app.name": "校园菜单",
  "app.tagline": "为大学生量身定制",

  "tabs.thisWeek": "本周菜单",
  "tabs.grocery": "购物清单",
  "tabs.preferences": "偏好",
  "tabs.settings": "设置",

  "common.loading": "加载中…",
  "common.today": "今天",
  "common.current": "当前",
  "common.cancel": "取消",
  "common.done": "完成",
  "common.close": "关闭",
  "common.back": "返回",
  "common.serving": "人份",
  "common.servings": "人份",

  "week.title": "本周菜单",
  "week.empty.title": "本周还没安排菜单",
  "week.empty.text": "根据你的偏好，一键生成一整周省时又好吃的家常菜。",
  "week.generate": "生成新菜单",

  "meal.breakfast": "早餐",
  "meal.lunch": "午餐",
  "meal.dinner": "晚餐",

  "grocery.title": "购物清单",
  "grocery.progress": "已勾选 {checked} / {total}",
  "grocery.clearDone": "清除已购",
  "grocery.share": "分享",
  "grocery.empty.title": "还没有购物清单",
  "grocery.empty.text": "先生成一份本周菜单，购物清单会自动出现在这里。",

  "category.Produce": "蔬果",
  "category.Dairy": "奶蛋",
  "category.Pantry": "干货",
  "category.Protein": "肉类",
  "category.Frozen": "冷冻",
  "category.Other": "其他",

  "prefs.title": "偏好设置",
  "prefs.subtitle": "这些设置将决定下一次生成的菜单。",
  "prefs.dietary": "饮食限制",
  "prefs.meals": "每天几餐",
  "prefs.budget": "每周预算",
  "prefs.skill": "厨艺水平",

  "diet.vegetarian": "素食",
  "diet.vegan": "纯素",
  "diet.gf": "无麸质",
  "diet.df": "无乳制品",

  "skill.Beginner": "新手",
  "skill.Intermediate": "进阶",
  "skill.Confident": "熟练",

  "budget.Tight": "紧张（¥200）",
  "budget.Moderate": "适中（¥400）",
  "budget.Comfortable": "宽裕（¥700）",

  "meals.Dinner": "仅晚餐",
  "meals.Lunch+Dinner": "午餐+晚餐",
  "meals.All": "三餐都要",

  "settings.title": "设置",
  "settings.language": "语言",
  "settings.theme": "主题颜色",
  "settings.themeHint": "为应用挑一个主题色。",

  "theme.red": "红",
  "theme.orange": "橙",
  "theme.yellow": "黄",
  "theme.cyan": "青",
  "theme.blue": "蓝",
  "theme.purple": "紫",
  "theme.pink": "粉",

  "recipe.notFound": "未找到菜谱。",
  "recipe.goBack": "返回",
  "recipe.ingredients": "食材",
  "recipe.instructions": "做法",
  "recipe.swap": "换一道",
  "recipe.minutes": "{n}分钟",

  "share.title": "分享菜单",
  "share.subtitle": "把本周菜单与购物清单分享给朋友。",
  "share.preview.header": "本周菜单",
  "share.preview.grocery": "购物清单",
  "share.preview.items": "共 {n} 项",
  "share.preview.more": "还有 {n} 项",
  "share.preview.footer": "由「校园菜单」生成",
  "share.save": "保存图片",
  "share.send": "分享",
  "share.saved": "已保存到相册",
  "share.savedFail": "保存图片失败。",
  "share.permission": "未获得相册权限。",
  "share.shareFail": "当前设备不支持分享。",
  "share.webOnly": "上方为分享预览图。",

  "day.0.short": "周日",
  "day.1.short": "周一",
  "day.2.short": "周二",
  "day.3.short": "周三",
  "day.4.short": "周四",
  "day.5.short": "周五",
  "day.6.short": "周六",
};

const zhHant: Dict = {
  "app.name": "校園菜單",
  "app.tagline": "為大學生量身打造",

  "tabs.thisWeek": "本週菜單",
  "tabs.grocery": "購物清單",
  "tabs.preferences": "偏好",
  "tabs.settings": "設定",

  "common.loading": "載入中…",
  "common.today": "今天",
  "common.current": "目前",
  "common.cancel": "取消",
  "common.done": "完成",
  "common.close": "關閉",
  "common.back": "返回",
  "common.serving": "人份",
  "common.servings": "人份",

  "week.title": "本週菜單",
  "week.empty.title": "本週還沒安排菜單",
  "week.empty.text": "根據你的偏好，一鍵生成整週省時又好吃的家常菜。",
  "week.generate": "生成新菜單",

  "meal.breakfast": "早餐",
  "meal.lunch": "午餐",
  "meal.dinner": "晚餐",

  "grocery.title": "購物清單",
  "grocery.progress": "已勾選 {checked} / {total}",
  "grocery.clearDone": "清除已購",
  "grocery.share": "分享",
  "grocery.empty.title": "還沒有購物清單",
  "grocery.empty.text": "先生成一份本週菜單，購物清單會自動出現在這裡。",

  "category.Produce": "蔬果",
  "category.Dairy": "奶蛋",
  "category.Pantry": "乾貨",
  "category.Protein": "肉類",
  "category.Frozen": "冷凍",
  "category.Other": "其他",

  "prefs.title": "偏好設定",
  "prefs.subtitle": "這些設定將決定下一次生成的菜單。",
  "prefs.dietary": "飲食限制",
  "prefs.meals": "每天幾餐",
  "prefs.budget": "每週預算",
  "prefs.skill": "廚藝程度",

  "diet.vegetarian": "素食",
  "diet.vegan": "純素",
  "diet.gf": "無麩質",
  "diet.df": "無乳製品",

  "skill.Beginner": "新手",
  "skill.Intermediate": "進階",
  "skill.Confident": "熟練",

  "budget.Tight": "拮据（NT$900）",
  "budget.Moderate": "適中（NT$1800）",
  "budget.Comfortable": "寬裕（NT$3000）",

  "meals.Dinner": "僅晚餐",
  "meals.Lunch+Dinner": "午餐+晚餐",
  "meals.All": "三餐都要",

  "settings.title": "設定",
  "settings.language": "語言",
  "settings.theme": "主題顏色",
  "settings.themeHint": "為應用挑選一個主題色。",

  "theme.red": "紅",
  "theme.orange": "橙",
  "theme.yellow": "黃",
  "theme.cyan": "青",
  "theme.blue": "藍",
  "theme.purple": "紫",
  "theme.pink": "粉",

  "recipe.notFound": "找不到食譜。",
  "recipe.goBack": "返回",
  "recipe.ingredients": "食材",
  "recipe.instructions": "做法",
  "recipe.swap": "換一道",
  "recipe.minutes": "{n}分鐘",

  "share.title": "分享菜單",
  "share.subtitle": "把本週菜單與購物清單分享給朋友。",
  "share.preview.header": "本週菜單",
  "share.preview.grocery": "購物清單",
  "share.preview.items": "共 {n} 項",
  "share.preview.more": "還有 {n} 項",
  "share.preview.footer": "由「校園菜單」生成",
  "share.save": "儲存圖片",
  "share.send": "分享",
  "share.saved": "已儲存到相簿",
  "share.savedFail": "儲存圖片失敗。",
  "share.permission": "未取得相簿權限。",
  "share.shareFail": "目前裝置不支援分享。",
  "share.webOnly": "上方為分享預覽圖。",

  "day.0.short": "週日",
  "day.1.short": "週一",
  "day.2.short": "週二",
  "day.3.short": "週三",
  "day.4.short": "週四",
  "day.5.short": "週五",
  "day.6.short": "週六",
};

const translations: Record<Locale, Dict> = {
  "zh-Hans": zhHans,
  "zh-Hant": zhHant,
  en,
};

export function t(
  locale: Locale,
  key: string,
  params?: Record<string, string | number>,
): string {
  const dict = translations[locale] || en;
  let value = dict[key] ?? en[key] ?? key;
  if (params) {
    Object.keys(params).forEach((p) => {
      value = value.replace(new RegExp(`\\{${p}\\}`, "g"), String(params[p]));
    });
  }
  return value;
}

export function getDayLabel(
  locale: Locale,
  dayIndex: number,
  isToday: boolean,
): string {
  if (isToday) return t(locale, "common.today");
  return t(locale, `day.${dayIndex}.short`);
}

export function getMealTypeLabel(
  locale: Locale,
  type: "breakfast" | "lunch" | "dinner",
): string {
  return t(locale, `meal.${type}`);
}
