const colors = {
  light: {
    text: "#222222",
    tint: "#ff6b5b",
    background: "#fcfbfa",
    foreground: "#222222",
    card: "#ffffff",
    cardForeground: "#222222",
    primary: "#ff6b5b",
    primaryForeground: "#ffffff",
    secondary: "#ffe8e5",
    secondaryForeground: "#ff6b5b",
    muted: "#f0ece9",
    mutedForeground: "#736b68",
    accent: "#ffe8e5",
    accentForeground: "#222222",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5deda",
    input: "#e5deda",
  },
  dark: {
    text: "#fcfbfa",
    tint: "#ff6b5b",
    background: "#1a1818",
    foreground: "#fcfbfa",
    card: "#222222",
    cardForeground: "#fcfbfa",
    primary: "#ff6b5b",
    primaryForeground: "#ffffff",
    secondary: "#3d2b29",
    secondaryForeground: "#ff6b5b",
    muted: "#2a2625",
    mutedForeground: "#a09895",
    accent: "#3d2b29",
    accentForeground: "#fcfbfa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3d3836",
    input: "#3d3836",
  },
  radius: 16,
};

export default colors;